[package]
name = "wmt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26.1"
clap = "2.33.3"

[[bin]]
name = "wmt"
path = "src/main.rs"

[lib]
name = "wmt"
path = "src/lib.rs"
